# Generated by Django 3.0.3 on 2020-04-05 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200404_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='first_name',
            new_name='USU_APELLIDO',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='USU_CONTRASENIA',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='USU_CORREO',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='last_name',
            new_name='USU_NOMBRE',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='rut',
            new_name='USU_RUT',
        ),
    ]
