# Generated by Django 3.0.3 on 2020-04-05 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200404_2312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
