# Generated by Django 3.0.3 on 2020-04-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PARTNER',
            fields=[
                ('USU_RUT', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('USU_NOMBRE', models.CharField(max_length=30)),
                ('USU_APELLIDO', models.CharField(max_length=30)),
                ('USU_CORREO', models.CharField(max_length=100)),
                ('USU_CONTRASENIA', models.CharField(max_length=100)),
            ],
        ),
    ]
